### ISSUE TITLE
Doesn't work in April 1 build

### ISSUE THREAD

**Issue by slate0** [notmike101/discord-channel-collapse-button#12]
Hello, I really appreciate you taking the time to update this project.
I just wanted to note that I can not get it to work in the April 1 build of discord (I can't find a better version number).  This is my first time so I might be making a mistake.

Steps (Windows 10 64 bit desktop app):
-ctrl-shift-i to open console, paste code and enter, 
-result:

```
ncaught TypeError: Cannot read property 'classList' of null
    at Object.addToolbarItem (<anonymous>:8:118)
    at <anonymous>:44:21
    at <anonymous>:46:3

addToolbarItem | @ | VM4826:8
-- | -- | --
  | (anonymous) | @ | VM4826:44
  | (anonymous) | @ | VM4826:46

```

**Comment by notmike101** [comment]
As this is no longer a maintained project (I should probably update the readme to reflect that), feel free to submit a pull request for any necessary changes for this to remain functional.

If I have time in the future, I'll update this, but as it stands, I do not.

**Comment by ThatGeekyWeeb** [comment]
@slate0 
I've forked and fixed this plugin, it operates perfectly now. 
I've also opened a PR and hopefully it will be merged
> #13
